export const BLOG_CREATE_REQUEST = 'BLOG_CREATE_REQUEST';
export const BLOG_CREATE_SUCCESS = 'BLOG_CREATE_SUCCESS';
export const BLOG_CREATE_FAIL = 'BLOG_CREATE_FAIL';

export const BLOG_GET_REQUEST = 'BLOG_GET_REQUEST';
export const BLOG_GET_FAIL = 'BLOG_GET_FAIL';
export const BLOG_GET_SUCCESS = 'BLOG_GET_SUCCESS';

export const BLOGS_GET_REQUEST = 'BLOGS_GET_REQUEST';
export const BLOGS_GET_FAIL = 'BLOGS_GET_FAIL';
export const BLOGS_GET_SUCCESS = 'BLOGS_GET_SUCCESS';
